name: "🐛 Bug Report"
description: Create a bug report for React Pill.
body:
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Console log output (if relevant)
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: input
    attributes:
      label: Which React Pill version are you using? (if relevant)
      description: "For example: 1.0.0, 1.1.0, etc"
  - type: input
    attributes:
      label: Which browser are you using? (if relevant)
      description: "For example: Chrome, Edge, Firefox, etc"
  - type: markdown
    attributes:
      value: |
        ### Screenshots
        If applicable, add screenshots to help explain your problem.
  - type: textarea
    attributes:
      label: Screenshots
      description: You can attach images by clicking this area to highlight it and then dragging files in.
      placeholder: Drag and drop screenshots here.