name: "🐛 Bug Report"
description: Create a bug report for React Pill.
body:
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Console log output (if relevant)
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: input
    attributes:
      label: Which React Pill version are you using? (if relevant)
      description: "For example: 1.0.0, 1.1.0, etc"
  - type: input
    attributes:
      label: Which browser are you using? (if relevant)
      description: "For example: Chrome, Edge, Firefox, etc"